create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    phone varchar(50) unique,
    password_hash varchar(255) not null,
    full_name varchar(150) not null,
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null,
    constraint ck_users_status check (status in ('ACTIVE', 'DISABLED'))
);

create table roles (
    id bigint generated by default as identity primary key,
    name varchar(30) not null unique,
    constraint ck_roles_name check (name in ('OWNER', 'ADMIN'))
);

create table user_roles (
    user_id bigint not null references users (id),
    role_id bigint not null references roles (id),
    primary key (user_id, role_id)
);

insert into roles (name) values ('OWNER'), ('ADMIN');
