create table vessels (
    id bigint generated by default as identity primary key,
    owner_id bigint not null references users (id),
    name varchar(150) not null,
    registration_number varchar(100) not null unique,
    vessel_type varchar(80) not null,
    status varchar(30) not null,
    reviewed_by bigint references users (id),
    reviewed_at timestamp with time zone,
    rejection_reason text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null,
    constraint ck_vessels_status check (status in ('PENDING', 'APPROVED', 'REJECTED'))
);

create index idx_vessels_owner_id_id on vessels (owner_id, id);
