create table routes (
    id bigint generated by default as identity primary key,
    code varchar(30) not null unique,
    name varchar(150) not null,
    origin varchar(100) not null,
    destination varchar(100) not null,
    service_fee numeric(12, 2) not null,
    active boolean not null default true,
    created_by bigint not null references users (id),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null,
    constraint ck_routes_service_fee_positive check (service_fee > 0)
);

create index idx_routes_active_id on routes (active, id);
