create table coupons (
    id bigint generated by default as identity primary key,
    code varchar(80) not null unique,
    owner_id bigint not null references users (id),
    amount numeric(12, 2) not null,
    status varchar(30) not null,
    expires_at timestamp with time zone not null,
    issued_by bigint not null references users (id),
    created_at timestamp with time zone not null,
    used_at timestamp with time zone,
    version bigint not null,
    constraint ck_coupons_amount_positive check (amount > 0),
    constraint ck_coupons_status check (status in ('ACTIVE', 'USED', 'EXPIRED', 'CANCELLED')),
    constraint ck_coupons_expiry_after_creation check (expires_at > created_at)
);

create index idx_coupons_owner_id_id on coupons (owner_id, id);
