create table bookings (
    id bigint generated by default as identity primary key,
    booking_number varchar(80) not null unique,
    requested_by bigint not null references users (id),
    vessel_id bigint not null references vessels (id),
    route_id bigint not null references routes (id),
    service_date date not null,
    service_fee numeric(12, 2) not null,
    status varchar(40) not null,
    reviewed_by bigint references users (id),
    reviewed_at timestamp with time zone,
    rejection_reason text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    version bigint not null,
    constraint ck_bookings_service_fee_positive check (service_fee > 0),
    constraint ck_bookings_status check (status in (
        'PENDING_PAYMENT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'ASSIGNED', 'COMPLETED'
    ))
);

create index idx_bookings_requested_by_id on bookings (requested_by, id);
