create table payments (
    id bigint generated by default as identity primary key,
    booking_id bigint not null references bookings (id),
    payer_id bigint not null references users (id),
    amount numeric(12, 2) not null,
    payment_method varchar(30) not null,
    status varchar(30) not null,
    transaction_reference varchar(100) not null unique,
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null,
    constraint ck_payments_amount_positive check (amount > 0),
    constraint ck_payments_method check (payment_method in ('COUPON')),
    constraint ck_payments_status check (status in ('PENDING', 'SUCCESS', 'FAILED'))
);

create unique index uq_successful_payment_per_booking
    on payments (booking_id)
    where status = 'SUCCESS';

create table coupon_redemptions (
    id bigint generated by default as identity primary key,
    coupon_id bigint not null unique references coupons (id),
    payment_id bigint not null unique references payments (id),
    amount_redeemed numeric(12, 2) not null,
    redeemed_at timestamp with time zone not null,
    constraint ck_coupon_redemptions_amount_positive check (amount_redeemed > 0)
);
