create table pilots (
    id bigint generated by default as identity primary key,
    employee_number varchar(80) not null unique,
    name varchar(150) not null,
    phone varchar(50),
    email varchar(255),
    status varchar(30) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null,
    constraint ck_pilots_status check (status in ('ACTIVE', 'INACTIVE'))
);

create index idx_pilots_status_id on pilots (status, id);
