create table booking_assignments (
    id bigint generated by default as identity primary key,
    booking_id bigint not null references bookings (id),
    pilot_id bigint not null references pilots (id),
    service_date date not null,
    assigned_by bigint not null references users (id),
    status varchar(30) not null,
    assigned_at timestamp with time zone not null,
    completed_at timestamp with time zone,
    constraint ck_booking_assignments_status check (status in ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

create unique index uq_active_assignment_per_booking
    on booking_assignments (booking_id)
    where status = 'ACTIVE';

create unique index uq_active_pilot_per_service_date
    on booking_assignments (pilot_id, service_date)
    where status = 'ACTIVE';
